spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingList?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: toor

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  #  sql:
  #    init:
  #      mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true


